#!/bin/sh

# Tweak maxlogitemlength - see http://tracker.clearfoundation.com/view.php?id=424
#-----------------------

CHECK=`grep ^maxlogitemlength /etc/dansguardian-av/dansguardian.conf`
if [ -z "$CHECK" ]; then
    logger -p local6.notice -t installer "app-content-filter-core - updating logging policy for long URLs"
    sed -i -e 's/#[[:space:]]*maxlogitemlength.*/maxlogitemlength = 400/' /etc/dansguardian-av/dansguardian.conf
fi

# Enable auto-tune by default on new installs (leave disabled on existing boxes)
#-------------------------------------------------------------------------------

if [ -e /etc/clearos/content_filter.conf ]; then
    logger -p local6.notice -t installer "app-content-filter-core - enabling auto-tuning"
    sed -i -e 's/auto_tune[[:space:]]*=.*/auto_tune = yes/' /etc/clearos/content_filter.conf
fi

# Set default filtergroupslist
#-----------------------------

logger -p local6.notice -t installer "app-content-filter-core - setting filter groups list"
echo "clearos_any_user" > /etc/dansguardian-av/lists/filtergroupslist

# Set tuning
#-----------

/usr/clearos/apps/content_filter/deploy/auto-tune

# Reload clearsyncd
#------------------

/sbin/service clearsyncd condrestart >/dev/null 2>&1
